matterpoll/matterpoll

server/command_test.go
server/poll.go
server/versions.go

Add api version to poll endpoints

---

Makefile

Link executables static

---

CHANGELOG.md
plugin.json

Release v0.0.2

---

.travis.yml

I don`t know how to generate the api key. Do you help with this @kaakaa?
Fixes #25

Build releases with travis

---

server/handler.go
server/handler_test.go
server/plugin.go

Add info to  /

---

README.md

Lets see if this fixes the problem. If it does we can merge. See https://pre-release.mattermost.com/core/pl/wim3gnm43tr55gac98fowk33jw

 Improve installation notes

---

server/command.go
server/command_test.go
server/handler_test.go
server/plugin.go

This should help debug some problem. The mock calls look ugly but i don't know how to do this better.
Fixes #39

Add logging

---

plugin.json
server/command.go
server/command_test.go
server/configuration.go
server/configuration_test.go
server/handler.go
server/plugin.go
server/plugin_test.go
server/utils.go
server/utils_test.go

Add config option for trigger

---

README.md
server/handler.go

Rename to Matterpoll

---

server/handler_test.go
server/plugin.go

Just a small changes, but it the old code looked ugly.

Simplify logging a bit

---

server/command.go
server/command_test.go
server/configuration.go
server/configuration_test.go
server/handler.go
server/handler_test.go
server/plugin.go
server/poll.go

There was actually some needed to get this working because `handleVote()` didn't updated the post until now.
I'm not 100% happy with adding `SiteURL` to `MatterpollPlugin` but I think its okay for now. We can work on this after #24 is merged.
i'm 2/5 on the text. If you have a better idea, go ahead and change it. 
Fixes #27

Show how many pepole have voted

---

README.md
build/manifest/Gopkg.lock
build/manifest/Gopkg.toml
build/manifest/vendor/github.com/mattermost/mattermost-server/model/channel.go
build/manifest/vendor/github.com/mattermost/mattermost-server/model/client4.go
build/manifest/vendor/github.com/mattermost/mattermost-server/model/config.go
build/manifest/vendor/github.com/mattermost/mattermost-server/model/post.go
build/manifest/vendor/github.com/mattermost/mattermost-server/model/search_params.go
build/manifest/vendor/github.com/mattermost/mattermost-server/model/team.go
build/manifest/vendor/github.com/mattermost/mattermost-server/model/utils.go
build/manifest/vendor/github.com/mattermost/mattermost-server/model/version.go
build/manifest/vendor/github.com/mattermost/mattermost-server/utils/markdown/autolink.go
build/manifest/vendor/github.com/mattermost/mattermost-server/utils/markdown/html.go
build/manifest/vendor/github.com/mattermost/mattermost-server/utils/markdown/inlines.go
server/Gopkg.lock
server/Gopkg.toml
server/command_test.go
server/handler.go
server/handler_test.go
server/poll.go

Update Mattermost to 5.3

---

server/command.go
server/command_test.go
server/handler.go
server/plugin.go

The best rule I came put with is:
- For author name: Use `GetDisplayName(model.SHOW_NICKNAME_FULLNAME)`
- For users at the end Poll screen:  Use `GetDisplayName(model.SHOW_USERNAME)`
As always this PR includes some refactoring. :wink: 
Fixes #52

Respect Teammate Name Display

---

plugin.json

Add link to repository in settings footer

---

server/handler.go
server/handler_test.go
server/plugin.go

Fixes #65 
And includes some code improvents

Fix user icon with subpath

---

CHANGELOG.md
plugin.json

Release 0.1

---

README.md

See https://pre-release.mattermost.com/core/pl/poghmso8p3ritermok1667ofrw

Add Troubleshooting for https

---

server/api.go
server/api_test.go

Specify http method & cache user image

---

server/api.go
server/api_test.go
server/plugin.go

@Twilek-de feel free to test this PR
Fixes #74

Allow System Admins to delete and end polls

---

server/command_test.go
server/poll.go

Add indicator for poll settings

---

plugin.json
server/plugin/manifest.go

Requires
- #85 
- #93 
Fixes #78

Release 1.0.0

---

README.md

@kaakaa if you think more informations are needed, feel free to propose them.

Add Contributing section

---

plugin.json
server/plugin/manifest.go

Bump version to 1.0.2

---

server/plugin/api.go
server/plugin/plugin.go
server/store/kvstore/poll.go
server/store/kvstore/store.go
server/store/kvstore/system.go
server/store/kvstore/upgrade.go
server/store/store.go
server/utils/testutils/data.go
server/utils/utils.go

This can be reviewed best via the individual commits.

Spring cleanup

---

server/store/kvstore/upgrade.go
server/store/kvstore/upgrade_test.go

Don't set database schema to patch versions

---

server/plugin/command.go

Fix auto comoplete hing.
Fixes #113

Fix command hint text

---

Makefile
README.md

Apply changes in https://github.com/mattermost/mattermost-plugin-sample/pull/27.
And remove troubleshooting for old version.

Replace tac with sed 

---

README.md

https://community.mattermost.com/core/pl/twpukgd787duxkrkyw1aqi7ach

Add bestpractices badge

---

server/plugin/configuration.go
server/plugin/plugin.go
server/plugin/plugin_test.go

This fixes _most_ of the cases.
Fixes https://github.com/matterpoll/matterpoll/issues/110

Don't start plugin if siteURL is not set

---

server/plugin/plugin.go
server/plugin/plugin_test.go

Remove unneeded UnregisterCommand call

---

CONTRIBUTING.md
README.md

This is a first draft for contribution guidelines. Any feedback is welcome!
@jasonblais If you have the time to share feedback, it would be appreciated.
Fixes #138
See https://github.com/matterpoll/matterpoll/pull/133 for details

Add contribution guideline

---

server/plugin/api_test.go
server/plugin/command_test.go
server/plugin/plugin_test.go
server/poll/poll_test.go
server/store/kvstore/store_test.go

Various code fixes 

---

assets/i18n/active.ja.json

Update ja translation for release 1.2.0

---

CONTRIBUTING.md
README.md

Only https://github.com/matterpoll/matterpoll/pull/175 needs a doc update. Hope I didn't missed something else.

1.2.0 Docs

---

.circleci/config.yml

This PR might fix the problem that pushing a tag doesn't kick any jobs.

Fix ci settings

---

server/plugin/api.go

Fix version in info endpoint

---

server/plugin/api.go
server/plugin/api_test.go

Correct message string.
Refs: https://community.mattermost.com/core/pl/1q6zzzcxijdpz8xo1ske6xaykr

Correct message string

---

go.mod
go.sum

Fix invalid link for dependencies

---

server/plugin/api.go
server/plugin/api_test.go

Revert `clicking` to `pressing`.
Refs: https://community.mattermost.com/core/pl/9oddgq6ek3d9zx1xg4mw3qthbr

Revert message string

---

assets/i18n/active.de.json
assets/i18n/active.en.json

Update german translation

---

webapp/package-lock.json

Generate by running `npm audit fix`

Update webapp depencies

---

go.mod
go.sum

Fix golangci

---

server/plugin/plugin.go
server/plugin/plugin_test.go

Fixes https://github.com/matterpoll/matterpoll/issues/262

Make use of EnsureBotOption

---

assets/i18n/active.pl.json

Add `few` and `many` translation for polish.
@amz @burasuk I don't know polish and can't confirm that this is a valid translation. Would you please give this a quick look?
Fixes https://github.com/matterpoll/matterpoll/issues/252

Add missing translations for polish

---

server/poll/metadata.go
server/poll/metadata_test.go

Follow up on https://github.com/matterpoll/matterpoll/pull/234

Add test for Metadata.ToMap()

---

.circleci/config.yml
Makefile

Basically a downstream from https://github.com/mattermost/mattermost-plugin-starter-template/pull/90
Fixes https://github.com/matterpoll/matterpoll/issues/271

Add golangci-lint to CI pipeline

---

CONTRIBUTING.md

Add instructions for development

---

go.mod
go.sum
server/plugin/plugin.go
server/plugin/plugin_test.go
server/store/kvstore/upgrade.go
server/store/kvstore/upgrade_test.go

Fixes https://github.com/matterpoll/matterpoll/issues/294
Fixes https://github.com/matterpoll/matterpoll/issues/265

Bump github.com/blang/semver to v4

---

webapp/src/components/post_type/__snapshots__/post_type.test.jsx.snap
webapp/src/components/post_type/action_view/action_button/__snapshots__/action_button.test.jsx.snap
webapp/src/components/post_type/fields/__snapshots__/fields_table.test.jsx.snap
webapp/src/components/post_type/fields/fields_table.jsx
webapp/src/components/post_type/fields/fields_table.test.jsx
webapp/tests/setup.js

Format field title in attachments

---

CONTRIBUTING.md
README.md
assets/i18n/active.ko.json

Add Korean(ko) translation
Signed-off-by: Ji-Hyeon Gim <potatogim@gluesys.com>

Add Korean(ko) translation

---

server/poll/poll.go
server/poll/poll_test.go
server/poll/transform.go

Set voter count to Metadata when progress option was set

---

server/plugin/api_test.go
server/plugin/command_test.go
server/utils/testutils/data.go

Fix broken tests and add test cases for #246

Fix tests for #246

---

server/plugin/api.go
server/plugin/api_test.go
server/plugin/command.go
server/plugin/command_test.go
server/poll/poll.go
server/utils/testutils/data.go

Prevent spoofing of requests

---

plugin.json

Per https://github.com/matterpoll/matterpoll/blob/master/.editorconfig the indentation should be 4 spaces, not 2.

Fix indentation in plugin.json

---

server/plugin/api.go
server/plugin/api_test.go
server/plugin/command.go
server/plugin/command_test.go
server/plugin/plugin.go

I shield away from adding a test for the `post.RootId != ""` case as this would require refactoring in way tests are setup.

Post responses in RHS

---

server/plugin/i18n.go

Fixes https://github.com/matterpoll/matterpoll/issues/336

Show default message if translation is missing

---

server/poll/poll.go
server/poll/poll_test.go

Fix how to check duplicated vote with multi votes setting

---

assets/i18n/active.ko.json

This PR updates Korean translation for 1.4.0
Signed-off-by: Ji-Hyeon Gim <potatogim@gluesys.com>

Update KR Translation for 1.4.0

---

plugin.json
server/plugin/manifest.go

This will be the release for the Marketplace. It has to wait until the Marketplace reviews are done.
Fixes https://github.com/matterpoll/matterpoll/issues/328

Release 1.4.0

---

server/plugin/plugin.go
server/plugin/plugin_test.go

Remove checkServerVersion #349
https://github.com/matterpoll/matterpoll/issues/349

#349 Remove checkServerVersion

---

server/plugin/api.go

Fixes https://github.com/matterpoll/matterpoll/issues/361

Allow empty string as third option in modal

---

CONTRIBUTING.md
README.md
assets/i18n/active.ru.json

Add Russian localization, update README.md and CONTRIBUTING.md .

Add Russian localization 

---

README.md

Include a link to releases and information on how to download, install, and upgrade an air gapped installation.

Add offline install/upgrade instructions

---

assets/i18n/active.zh-CN.json

Hi, get pinged by mistake but found an update of the translation resource so I followed it up. 😃

Update the simplified chinese translation

---

assets/i18n/active.es.json

Update Spanish translation for 1.5.0

---

assets/i18n/active.zh-TW.json

Update Traditional Chinese translation

#420 Update the Traditional Chinese translation

---

webapp/package-lock.json
webapp/package.json
webapp/src/actions/poll_metadata.js
webapp/src/actions/poll_metadata.test.js

Fix Unhandle Promise Rejection for poll_metadata.test.js

---

assets/i18n/active.de.json

Fixes a small grammar error in the german translation.

Fix grammar in translation (de)

---

assets/i18n/active.de.json

Update German Translation for 1.6.0

---

CONTRIBUTING.md
README.md
plugin.json
server/store/kvstore/store_test.go
server/store/kvstore/upgrade.go

refs #476 
Update versions and documentation for 1.6.0 release.

Updates for 1.6

---

plugin.json
server/store/kvstore/store_test.go
server/store/kvstore/upgrade.go

This patch release has a fix of environment issue (#487).

Updates for 1.6.1

---

README.md

Add notes regarding Mobile app not supporting ExperimentalUI

---

assets/i18n/active.en.json
assets/i18n/active.ja.json

also update en message that was forgotten to update.

translate ja

---

assets/i18n/active.de.json

First time, done with github codespaces (thought, I do not need to clone ;). Hope it's correctly done ;)

German translation for Release 1.7.0 #546

---

assets/i18n/active.es.json

Sorry for the delay. I must have missed the ping. Better late than never!

Update Spanish translation for 1.7.0

---

plugin.json
server/store/kvstore/store_test.go
server/store/kvstore/upgrade.go

This patch release include a fix of compatibility issue (#564).

Updates for 1.7.1

---

CONTRIBUTING.md
README.md
assets/i18n/active.sv.json

i18n: New translation - Swedish
