matterpoll/matterpoll

- Taskfile.yml
This fixes an issue where the task would fail if `dist`already exists.
> Fix taskfile

- server/command.go
- server/command_test.go
Matterpoll can set their trigger word.
But even though trigger word isn't `matterpoll`, error message tell `matterpoll` as trigger word.
> Fix command error messages

- build/manifest/Gopkg.toml
- server/Gopkg.lock
- server/Gopkg.toml
- server/command_test.go
- server/plugin_test.go
- server/poll.go
- server/poll_test.go
This PR add `CreatedAt int64` to `Poll`. I chose `int64`because its used my Mattermost.
Testing this was a lit hard. I'm using https://github.com/bouk/monkey to replace the calls to `GetMillis()` by a static number. This ain't pretty, but it does the job. Otherwise we would have to do something like adding `TimeGenerator` to `MatterpollPlugin`.
I also fixed some Gopkg problems.
Fixes #43
> Add CreatedAt field to Poll

- Makefile
- server/command.go
- server/command_test.go
- server/handler_test.go
- server/plugin.go
- server/poll.go
Todo:
Based on https://github.com/matterpoll/matterpoll/pull/33/commits/05319b97e38409b62c567901e0a19e63c00dc25b
Fixes #17
> Serve user icon from local assets

- server/Gopkg.lock
- server/Gopkg.toml
There was an error with the current master. Since we are planing to release when 5.4 comes out, this PR lock the Mattermost dependency to the 5.4 release branch.
> Lock to 5.4 release branch

- server/api_test.go
- server/command_test.go
- server/configuration_test.go
This fixes all of the "how to name and rename the api object" problems. It think it the most clean solution.
> Move away from test global api objects

- server/Gopkg.lock
- server/Gopkg.toml
- server/api.go
- server/command.go
- server/command_test.go
- server/configuration.go
- server/configuration_test.go
- server/plugin.go
- server/plugin_test.go
- server/poll.go
- server/utils.go
- server/versions.go
Since plugin methods are called asynchrony `Config` could be changed any time. This PR fixes this by using a lock. It is pretty much a downstream of https://github.com/mattermost/mattermost-plugin-demo/pull/7.
The second commit fixes come linter issues. Some day I will learn to submit separate PRs for this. Sorry @kaakaa.
> Sync read and write to config

- README.md
- server/Gopkg.lock
- server/Gopkg.toml
- server/api.go
- server/plugin.go
- server/plugin_test.go
This PR makes use of `GetServerVersion()` and enforces a minimum Mattermost server version. It also bumps the minimum server version to 5.4. Otherwise we can't use `GetServerVersion()`.
> Enforce minimum server version

- server/plugin/command.go
- server/plugin/command_test.go
Typing `/poll "Something or other" yes no maybe` now shows:
This cover two cases:
- A unknown setting is provided
- Just two arguments are given e.g. `/poll "abc" "def"`
Fixes #101
> Don't post ephemeral message if query is invalid

- Makefile
- server/plugin/api.go
- server/plugin/api_test.go
We used to server files relative to the working directory.
But this can't be considered reliable. This commit changes the way we 
look for files looking for them relative to the executable path.  Since 
he know how the directories under the executable are strutured, this is 
a save way.
This commit also changes the tests accordingly.
@kaakaa One technical note: I don't know how to test `os.Executable()`'s error case. I tried to use monkey patching but it didn't work. See f10ecdbd9a9c5245212bb8810cb05bbf656d6a88.
@JamonBarns @geberl @m49808 @zetaab Please test this PR, if you have the time. You can use 
[com.github.matterpoll.matterpoll-1.0.1.tar.gz](https://github.com/matterpoll/matterpoll/files/2553310/com.github.matterpoll.matterpoll-1.0.1.tar.gz) or compile it yourself.
Fixes #91
> Serve logo relative to executable path

- server/plugin/api.go
If `request == nil` we can't use the information to send a ephemeral post. Since we don't have any information, there is nothing we can do here other then logging the error, right?
> Fix NPE in addOption

- assets/i18n/active.de.json
- assets/i18n/active.en.json
- assets/i18n/active.fr.json
- assets/i18n/active.ja.json
This PR fixes two things:
- Update `poll.message.totalVotes` as I forgot to pull the new translation from the source file
- Fix the double escaped `\` in `fr` and `ja` translation. See https://github.com/nicksnyder/go-i18n/issues/160 for more details.
> Fix translations

- assets/i18n/active.de.json
- assets/i18n/active.en.json
- server/Gopkg.lock
- server/Gopkg.toml
- server/plugin/api.go
- server/plugin/api_test.go
- server/plugin/command.go
- server/plugin/command_test.go
- server/plugin/configuration.go
- server/plugin/configuration_test.go
- server/plugin/plugin.go
- server/plugin/plugin_test.go
- server/store/kvstore/store.go
- server/utils/testutils/data.go
This PR makes use of the Bot Account feature coming in Mattermost v5.10.
Basically ever persistent post is now posted by the bot account. ~~Ephemeral messages are not, but this is because posting a ephemeral message as a bot account isn't supported at the moment.~~ This will be fixed with MM v5.12.
~~Please not that there are some bug in the server part. See https://community-daily.mattermost.com/core/pl/9oyf339pajfx3msy1t14fr9poh. Blocked until the webapp part of the feature is fully implemented.~~ All bugs are fixed!
The only "not bot" messages are the ones created in `api.go`. I will change this is a different PR.
Fixes #126
> Use Bot Account

- server/plugin/api.go
- server/plugin/api_test.go
- server/plugin/command.go
- server/plugin/plugin_test.go
This PR refactors `api.go` to be much more DRY and unify handling of `PostActionIntegrationRequest` and `SubmitDialogRequest`. The only functional change is that error thrown from the http handlers will now be logged. The log level is `warning`.
> Refactor api.go

- server/poll/poll.go
- server/poll/poll_test.go
Existing duplication check considers `No` and `No `(with trainling space) as different option.
It should be considered as same.
> Trim space when checking duplication

- Makefile
- build/custom.mk
- build/manifest/main.go
- server/plugin/api.go
- server/plugin/api_test.go
- server/plugin/command.go
- server/plugin/command_test.go
- server/plugin/manifest.go
- server/poll/poll.go
- server/poll/poll_test.go
- server/poll/transform.go
- server/poll/transform_test.go
- server/store/mockstore/store.go
- server/utils/testutils/data.go
This PR downstreams the latest changes from https://github.com/mattermost/mattermost-plugin-starter-template. Notable are:
- Custom makefile changes are now in `build/custom.mk`
- `check-style` also checks for `golint` compliance
- Renamed `PollSettings` to `Settings`. I've tested with an older version and this isn't a breaking change. But please double check and test.
> Downstream mattermost-plugin-starter-template

- server/utils/utils.go
- server/utils/utils_test.go
On iOS using an english keyboard, typing quotes yields curly quotes instead of straight quotes. Update the parser to handle these.
Fixes: https://mattermost.atlassian.net/browse/MM-17366
> MM-17366: handle curly quotes when parsing

- webapp/package.json
Make webapp code private, because webapp will never be published and should stay consiste with [mattermost-webapp](https://github.com/mattermost/mattermost-webapp/blob/master/package.json).
> Make webapp code private

- server/plugin/api.go
Otherwise the log is spammed with:
```
ERRO[2019-10-22T15:18:36.6914706+02:00] http: superfluous response.WriteHeader call from github.com/mattermost/mattermost-server/plugin.(*httpResponseWriterRPCServer).WriteHeader (http.go:27)  caller="http/server.go:3053" source=httpserver
```
> Remove superfluous header call

- server/plugin/i18n.go
- server/plugin/plugin_test.go
- server/utils/testutils/data.go
Per the MM docs  Default Client Language is used " for newly created users and pages where the user hasn’t logged in." (https://docs.mattermost.com/administration/config-settings.html#default-client-language), which fits our case much more.
> Use Default Client Language instead of Default Server Language

- .golangci.yml
- server/plugin/api.go
- server/plugin/api_test.go
- server/plugin/plugin.go
- server/plugin/plugin_test.go
Adds some useful linters and hardens the config. I also removed `gocyclo` because it's not a good metric.
Requires #243
> Tweak golangci config

- build/manifest/main.go
- go.mod
- go.sum
- server/main.go
- server/plugin/api.go
- server/plugin/api_test.go
- server/plugin/command.go
- server/plugin/command_test.go
- server/plugin/configuration.go
- server/plugin/configuration_test.go
- server/plugin/i18n_test.go
- server/plugin/plugin.go
- server/plugin/plugin_test.go
- server/poll/poll.go
- server/poll/poll_test.go
- server/poll/transform.go
- server/poll/transform_test.go
- server/store/kvstore/poll.go
- server/store/kvstore/poll_test.go
- server/store/kvstore/store.go
- server/store/kvstore/store_test.go
- server/store/kvstore/system.go
- server/store/kvstore/system_test.go
- server/store/kvstore/upgrade_test.go
- server/utils/testutils/data.go
- Bump MM server dependency
- run `npm audit fix --save`
> Bump dependency to Mattermost 5.18

- .codecov.yml
Decreasing coverage or missing coverage should not fail the CI. With these changes CI is always green for codecov.
> Don't report missing coverage as CI failure

- server/poll/poll.go
- server/poll/poll_test.go
- server/utils/testutils/data.go
`Poll.AnswerOption.Voter` was't correctly deep copied and therefore changes on the origin also changed the copy. This PR fixed it by correctly deep copying `Voters`.
Another carve is that `Voter` is `nil` for "new" options, but might become `[]string{}` when a user first votes for it and then votes for another option. To avoid this confusion in the future, `[]string{}` is now used for new options. Please note that polls fetched from the DB might still have a `nil` value, hence we have to still think about this case in the future.
Fixes https://github.com/matterpoll/matterpoll/issues/282
> Deep copy Voters

- server/plugin/plugin.go
- server/plugin/plugin_test.go
`OnConfigurationChange` might not be called after `OnActivate`. This PR ensures that the command is correctly registered by calling `RegisterCommand` in `OnActivate`.
See https://mattermost.atlassian.net/browse/MM-27174 for more details.
> Register Command in OnActivate

- assets/i18n/active.fr.json
As said in [#339](https://github.com/matterpoll/matterpoll/pull/339#issuecomment-704713346), I have been confused by the same text for "one" and "other" in `response.vote.multi.updated`.
Fixed.
> 🌐🐛 Fix FR translation

- CONTRIBUTING.md
- README.md
This PR corrects a simple typo in `README.md` and `CONTRIBUTING.md` (section Localization): `France` should be `French`.
> Use French instead of France

- go.mod
- go.sum
- server/plugin/api_test.go
- server/plugin/command_test.go
- server/plugin/plugin_test.go
- server/poll/poll_test.go
Since [bou.ke/monkey's license](https://github.com/bouk/monkey/blob/master/LICENSE.md) says that `I do not give anyone permissions to use this tool for any purpose.`, drop `bou.ke/monkey` and use [`undefinedlabs/go-mpatch`](https://github.com/undefinedlabs/go-mpatch) (released under MIT license) instead.
`undefinedlabs/go-mpatch` seems to be used by [Argo](https://github.com/argoproj/argo-cd/blob/master/go.mod#L67) which is the CNCF incubating project.
> Drop bou.ke/moneky

- .golangci.yml
- go.mod
- go.sum
- server/plugin/api.go
- server/plugin/command.go
- server/plugin/plugin.go
- server/plugin/plugin_test.go
- server/poll/poll.go
- server/poll/transform.go
- server/utils/i18n.go
- server/utils/i18n_test.go
- server/utils/testutils/i18n.go
- webapp/package-lock.json
- webapp/package.json
#404 replaced i18n package with `mattermost-plugin-api/i18n`, but since then, `goi18n extract` command doesn't extract any messages. It's because `goi18n extract` command extracts only messages declared in `github.com/nicksnyder/go-i18n/v2/i18n.Message` struct.
https://github.com/nicksnyder/go-i18n/blob/c587b0dfc11a01d42c0c5f9cea07d040f7a10788/v2/goi18n/extract_command.go#L285
This PR switch back to use `github.com/nicksnyder/go-i18n/v2/i18n.Message` for messages.
* Create `Bundle` struct in `utils` package
* Since Matterpoll depends i18n functionality in `plugin` and `poll` packages, i18n functionality should be in a package independent of these two.
* To avoid confusion with nicksnyder's i18n package, avoid to use the name `i18n`
* To avoid cyclic import, move `poll.ErrorMessage` to …
> Fix a problem in which the `goi18n extract` command did not extract messages

- .circleci/config.yml
Since 2 weeks ago, CI always fails.
```
#!/bin/bash -eo pipefail
make test
cd webapp && /usr/local/bin/npm install
make: *** [Makefile:81: webapp/node_modules] Terminated
Too long with no output (exceeded 10m0s): context deadline exceeded
```
This would be introduced by GitHub diabling cloning repo via git protocol. refs: https://github.com/npm/cli/issues/4896
This PR fixes the CI issue by forcing to always use https protocol when resolving npm dependencies.
---
* This PR fix CI builds on CircleCI, but fresh build on local machine with npm v6 still be very slow (about 10 and more mins on my machine)
* This changes will be removed after upgrading npm on CI environment to v7
* FYI: Changing npm dependencies from `github:mattermost/...` to `https://github.com/mattermost/...` in …
> Fix ci error

- server/plugin/plugin.go
- server/plugin/plugin_test.go
- server/utils/testutils/data.go
fixes #440
Note: Fullname in existing polls that is already shown will be changed when any update (vote, add option, reset votes) is made to the poll.
> Don't show user's full name when PrivacySettings.ShowFullName is disabled

- webapp/webpack.config.js
I tested this with ExperimentalUI setting on Mattermost v6.3.10, and it works fine.
refs:
* https://github.com/mattermost/mattermost-plugin-starter-template/pull/169
* https://mattermost.atlassian.net/browse/MM-47046
TODO:
- ~~[ ] It might be needed to add other packages [refs](https://github.com/mattermost/mattermost-plugin-starter-template/pull/169#issuecomment-1250414723)~~
- This should be fixed by another PR if needed
> Use version of React DOM provided by web app

- .golangci.yml
fixes #433 
When detecting `MustLocalize` in code, forbidigo show the following warning.
```
$ make check-style
...
Running golangci-lint
golangci-lint run ./...
server/hoge.go:7:3: use of `loc.MustLocalize` forbidden because "MustLocalize may cause panic such as #252, use one of localize functions in utils package instead" (forbidigo)
loc.MustLocalize(nil)
^
make: *** [check-style] Error 1
```
> Add linter(forbidigo) to prevent from using MustLocalize

- webapp/package-lock.json
- webapp/package.json
fixes #469 
The following error log of #469 said that `marked` cannot handle inline latex correctly.
```
Uncaught (in promise) TypeError: this.renderer.inlinelatex is not a function
at u.renderTokens (marked.js:887:30)
at u.output (marked.js:852:15)
at i.tok (marked.js:1289:50)
at i.parse (marked.js:1146:17)
at i.parse (marked.js:1133:17)
at f (marked.js:1495:19)
at h (index.ts:36:12)
at d (text_formatting.tsx:237:18)
at o.value (com.github.matterpoll.matterpoll_eda8fdcb9a124401_bundle.js:319:287466)
at Ho (react-dom.production.min.js:187:188)
```
The cause of #469 is that the version of `marked` that Matterpoll depends on is old and doesn't support inline latex. So updating `marked` version fixes #469.
> Update `marked` version

- README.md
Since the release of Mattermost v9, Matterpoll no longer be published from the Mattermost In-App Marketplace. Therefore, the Marketplace instructions is removed from the documentation.
> remove description about marketplace

- README.md
A possible issue as reported in #511 is that the server settings for maximum file size is smaller than the plugin file, the upload will fail with the message "Received invalid response from the server.".
This PR adds this issue and its solution to the Troubleshooting section of the README.md.
> Add plugin file size upload issue solution in README.md

- assets/i18n/active.en.json
- server/poll/transform.go
- server/poll/transform_test.go
- webapp/src/components/post_type/action_view/__snapshots__/action_view.test.jsx.snap
- webapp/src/components/post_type/action_view/action_view.test.jsx
There was an inconsistent capitalization between "Reset your vote" and "Add Option", "End Poll", "Delete Poll". Now  "Reset your vote" has been replaced with  "Reset Your Vote".
Closes #497
> fix: inconsistent capitalization in "Reset your vote"

- plugin.json
I tried to run the plugin on arm64, it didn't work, I noticed that there are actually arm64 builds in the server/dist folder, but they are missing from the plugin.json. Patched it and so far it seems to work
> Add missing executables to plugin.json

- .github/workflows/cd.yml
- .github/workflows/ci.yml
https://github.com/matterpoll/matterpoll/actions/runs/9129665836/job/25104751370#step:4:210
https://github.com/matterpoll/matterpoll/actions/runs/9129665836/job/25104922063#step:3:1
Release job was failed, (I guess) because of version conflicts between `actions/upload-artifact (v4)` and `actions/download-artifact (v3)`.   
Current workflow uses `mattermost/actions-workflows/.github/workflows/plugin-ci.yml@main` which depends `actions/upload-artifact (v4)`, and hard-coded `actions/download-artifact (v3)`.  
https://github.com/matterpoll/matterpoll/blob/0fbc18bf48371954a386098d7793694d1196d6e4/.github/workflows/ci.yml#L30
This PR introduce `community-plugin-ci/cd.yml` and version conflicts would be resolved (https://github.com/mattermost/actions-workflows/pull/44 was merged at nicely …
> Introduce community-plugin-ci/cd.yml

- server/poll/poll.go
fix #562 
Since the poll craeted by Matterpoll v1.6 or before doens't have `AnonymousCreator` setting, atomic transaction will be failed. Set omitempty to `AnonymousCreator` to avoid this error.
After merging this, get ready for releasing v1.7.1.
---
An upgrade script to update data within the KV Store could be considered, but it would need to be run every time a release that has new field for Poll/Settings. Therefore, a simpler approach using omitempty was adopted. The upgrade script will only be used when it is necessary to set specific initial values.
> Set omitempty to AnonymousCreator setting

- plugin.json
- server/store/kvstore/store_test.go
- server/store/kvstore/upgrade.go
refs #562, #564 
My bad, #564 doesn't resolve the issue completely.
If the poll with `{..., AnonymousCreator: false}` stored already by Matterpoll v1.7.0, `omitempty` will remove `AnonymousCreate: false` in existing data, and cause atomic transaction failure again.
To avoid atomic transaction failure related `AnonymousCreator` setting, we have to migrate existing data when upgrading.
> Add upgrade script to add AnonymousCreator setting to existing polls
